services:
  - type: web
    name: studio-kolbramah-api
    runtime: python
    plan: free
    region: ohio
    rootDir: backend
    buildCommand: pip install -e . && pip install bcrypt==4.1.3
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: studio-kolbramah-db
          property: connectionURI
      - key: REDIS_URL
        value: ""
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: S3_ENDPOINT_URL
        value: ""
      - key: CORS_ORIGINS
        value: '["https://studio-kolbramah-radio.vercel.app","http://localhost:3000"]'
      - key: APP_DEBUG
        value: "false"
      - key: APP_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.12.3"

databases:
  - name: studio-kolbramah-db
    plan: free
    databaseName: kolbramah
    user: radio
    region: ohio
